baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Blog Belajar Kode'
theme = 'dream'
defaultContentLanguage = 'en'

[params]
lightTheme = "emerald"
darkTheme = "forest"

avatar = "/img/gl.png"
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true